### PR TITLE
Fixes #127 Check for existence of gdiImage comes to late

### LINKED ISSUE #127: DrawImage draws allways the same (first) image
!!!!! If you think there is a bug in PDFsharp then please use the IssueSubmissionTemplate to make the issue replicable.  
!!!!! https://docs.pdfsharp.net/General/IssueReporting.html
!!!!! => Sorry, but this link doesn't work

# Reporting an Issue Here
When creating an PDF with three different Images, using XGraphics.DrawImage, the resulting PDF schould show up three different images.

## Actual Behavior
The resulting pdf shows up the same (first) image for three times.
This happend, if PDFSharp 6.1.0 is used
This does not happen, if PDFSharp 6.0.0 is used.

## Steps to Reproduce the Behavior
!!!!!  We strongly recommend using the IssueSubmissionTemplate to make sure we can replicate the issue.  
!!!!!  https://docs.pdfsharp.net/General/IssueReporting.html
!!!!!  => sorry, this link does not work.

Download Solution from embedded zip File.
Compile Solution using NuGet Package PDFSharp6.1.0
Run the compiled Program. This will produce the wrong result.
(file PdfSharpTest1.pdf in the Solution Folder)

Compile Solution using NuGet Package PDFSharp6.0.0
Run the compiled Program. This will produce the correct result.
(file PdfSharpTest1.pdf in the Solution Folder)

[PdfSharpTest1.zip](https://github.com/user-attachments/files/15926908/PdfSharpTest1.zip)

This sample project contains 2 PDF Files. These are the results when Project is compiled with PDFSharp 6.0.0 oder PDFSharp 6.1.0
The PDF named PdfSharpTest1-Version6.0.0.pdf contains the expected result.
The PDF named PdfSharpTest1-Version6.1.0.pdf contains the wrong result.

### PR DESCRIPTION
**Pull request by th-joerger**
I encountered the same problem as #127 in my production environment. Several customers have been severly affected with hundreds of wrongly printed qr codes.

The culprit seems to be this [dysfunctional code](https://github.com/empira/PDFsharp/blob/fd6d603d81ab42a3fab508fc65d56322b4ff2760/src/foundation/src/PDFsharp/src/PdfSharp/Pdf.Advanced/PdfImageTable.cs#L86-L106):

```
                    else if (image._stream != null!)
                    {
                        if (image._stream is MemoryStream ms)
                        {
                            var md5 = System.Security.Cryptography.MD5.Create();
                            var hash = md5.ComputeHash(ms);
                            image._path = "*md5:" + HashToString(hash);
                        }
                        else
                        {
                            // TODO Use hash code.
                            image._path = "*" + Guid.NewGuid().ToString("B");
                        }
                    }
#if GDI
                    else if (image._gdiImage != null!)
                    {
                        // TODO Use hash code.
                        image._path = "*" + Guid.NewGuid().ToString("B");
                    }
#endif
```

The md5 is always ``*md5:d41d8cd98f00b204e9800998ecf8427e`` which is the md5 hash of an empty input. The stream ``image._stream`` is already consumed when computing the hash, because in GDI in [XImage.cs](https://github.com/empira/PDFsharp/blob/fd6d603d81ab42a3fab508fc65d56322b4ff2760/src/foundation/src/PDFsharp/src/PdfSharp/Drawing/XImage.cs#L194-L202), the stream is already used to create an Image.

The work around for GDI with the check for the existence of ``image._gdiImage`` comes to late after the md5 hash is already computed.

When the memory stream is reset, everything works as expected.

```
                        if (image._stream is MemoryStream ms)
                        {
                            ms.Seek(0, SeekOrigin.Begin); // make sure, ms is not already consumed
                            var md5 = System.Security.Cryptography.MD5.Create();
                            var hash = md5.ComputeHash(ms);
                            image._path = "*md5:" + HashToString(hash);
                        }
```

So, I think the fix is, to check for the existence of ``image._gdiImage`` before computing the md5 hash. I send you a PR including a test. I would also appreciate you properly merging PRs instead of simply copying the code and squashing my contribution.

### CODE REVIEW

**Comment by ThomasHoevel** [comment]
Thanks for your contribution.
We already fixed that issue in our internal repository and our solution is much simpler than yours.

>  I would also appreciate you properly merging PRs instead of simply copying the code and squashing my contribution.

This is a repository we use to publish released versions, it is not the repository we use for development.

**Comment by th-joerger** [comment]
Thank you for your kind response. When do you plan to release your much simpler solution?

> This is a repository we use to publish released versions, it is not the repository we use for development.

Can you point me to the repository for development? I could not find it.

**Comment by ThomasHoevel** [comment]
The bug has been fixed in PDFsharp without using any code from this PR.

It spoils the idea of the ImageSelector class to check for GdiImage before checking for MemoryStream.

**Comment by th-joerger** [comment]
> It spoils the idea of the ImageSelector class to check for GdiImage before checking for MemoryStream.

But this was exactly, what I suggested and fixed in the PR. You need to check GdiImage before you check MemoryStream.

The ImageSelector class does currently **NOT** (also in [today's release](https://github.com/empira/PDFsharp/blob/1956cbf803892a7d27515c35052e85d254154577/src/foundation/src/PDFsharp/src/PdfSharp/Pdf.Advanced/PdfImageTable.cs#L86-L107)) check GdiImage before checking for MemoryStream.

I also implemendet a Todo: Hash-Compare of GdiImages.

**Pull request closed without merging**
