### PR TITLE
PdfSharp core project now multi-targets netstandard2.0 + net6.0

### PR DESCRIPTION
**Pull request by julienrffr**
At this point, only PdfSharp core project has been taken care of.

It works well on .net6 and .net7.
But there is an error on .net48 around font resolver.

Feel free to contribute.

### CODE REVIEW

**Comment by ThomasHoevel** [comment]
One compile-time error after cloning the repository that could easily be resolved.
111 unit tests failing. Still a long way to go.

I'm afraid our software architect will not accept the change from .NET6 to .netstandard20 in the project files.

**Comment by ThomasHoevel** [comment]
Fonts do not work with any .NET 4.x version.

**Comment by ThomasHoevel** [comment]
The PDFsharp project has a define for "NET_ZIP". Fonts work with .NET 4.x when "NET_ZIP" is not defined.

**Comment by julienrffr** [comment]
> The PDFsharp project has a define for "NET_ZIP". Fonts work with .NET 4.x when "NET_ZIP" is not defined.

Thanks for the hint @ThomasHoevel.

I've made some changes:

- PdfSharp core multi-targets netstandard2.0 + net6.0
- When NET_ZIP is defined AND it runs under net6.0 or above, it uses NET_ZIP capabilities
- When NET_ZIP is not defined or netframework, it uses internal implementation of SharpZipLIb instead of NET_ZIP capabilities
- Unit tests are all fixed

HelloWorld project can be ran as net48, and it works fine thanks to netstandard2.0 compatibility.

Any thoughts?

**Comment by julienrffr** [comment]
NB: this feature is available in [PDFsharp-extended nuget package](https://www.nuget.org/packages/PDFsharp-extended/)

**Comment by julienrffr** [comment]
Hi @ThomasHoevel 
I see you've made a preview release with the support for netstandard 2.0, that's great!
I see you removed the NET_ZIP flag and all SharpZibLib classes, how did you manage for netstandard2.0? What is the replacement? Could you explain a bit please?

**Comment by StLange** [comment]
Is done with 6.1.

**Pull request closed without merging**
